from CFG import CFG
from util import initializeCFG, generatePalindrome, testParser, checkString

grammar = CFG(0,0,0)
initializeCFG(grammar)

randomPalindrome = generatePalindrome(grammar, grammar.startSymbol)
print("Random Palindrome: ", randomPalindrome)


testParser(grammar, 5)

userInput = input("Enter a string to test if it is a palindrome: ")
if checkString(grammar, userInput):
    print("The string is generated by the CFG")
else:
    print("The string is not generated by the CFG.")